# Generated by Django 2.1.1 on 2018-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('a', 'male'), ('b', 'female'), ('c', 'Other'), ('d', 'Prefer not to disclose')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='LevelofStudy',
            field=models.CharField(choices=[('a', '1st Year'), ('b', '2nd Year'), ('c', '3rd Year'), ('d', '4th Year'), ('e', '5th Year or beyond'), ('f', 'Prefer not to disclose')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='Race',
            field=models.CharField(choices=[('a', 'White'), ('b', 'Black or African American'), ('c', 'Native American'), ('d', 'Asian'), ('e', 'Native Hawaiian or other Pacific Islander'), ('f', 'Latino or Latin American'), ('g', 'Other'), ('h', 'Two or more races'), ('i', 'Prefer not to disclose')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='Resume',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='conductBox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='dietRestrictions',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='gradYear',
            field=models.CharField(choices=[('a', '2019'), ('b', '2020'), ('c', '2021'), ('d', '2022'), ('e', '2023'), ('f', '2024'), ('g', '2025')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='meme',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='shareBox',
            field=models.BooleanField(default=False),
        ),
    ]
