# Generated by Django 2.0.6 on 2018-09-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('a', 'male'), ('b', 'female'), ('c', 'non-binary'), ('d', 'transgender'), ('e', 'other'), ('f', 'I prefer not to answer')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='LevelofStudy',
            field=models.CharField(choices=[('a', 'Freshman'), ('b', 'Sophomore'), ('c', 'Junior'), ('d', 'Senior'), ('e', 'Graduate Student')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='Race',
            field=models.CharField(choices=[('a', 'American Indian or Alaskan Native'), ('b', 'Asian or Pacific Islander'), ('c', 'Black or African American'), ('d', 'Hispanic'), ('e', 'White / Caucasian'), ('f', 'Multiple ethnicity / Other'), ('g', 'I prefer not to answer')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='Resume',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='conductBox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='dietRestrictions',
            field=models.CharField(choices=[('a', 'Vegetarian'), ('b', 'Vegan'), ('c', 'Gluten Free'), ('d', 'Kosher'), ('e', 'Diary Free'), ('f', 'None')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='gradYear',
            field=models.CharField(choices=[('a', '2018'), ('b', '2019'), ('c', '2020'), ('d', '2021'), ('e', '2022')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(blank=True, help_text='Format: ***********; digits only', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='questions',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='shareBox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Format: MM-DD-YYYY', null=True),
        ),
    ]
