# Generated by Django 2.0.6 on 2018-09-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0002_auto_20180924_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='meme',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
