# Generated by Django 2.1.2 on 2018-10-02 06:49

from django.db import migrations, models
import landingapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0002_auto_20181001_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Resume',
            field=models.FileField(default='', upload_to='uploads/', validators=[landingapp.validators.validate_file_extension]),
        ),
    ]
