# Generated by Django 2.0.7 on 2018-09-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0002_auto_20180923_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Resume',
            field=models.FileField(default='', upload_to='resumes/%Y/%m/%d'),
        ),
    ]
