# Generated by Django 2.0.6 on 2018-10-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0003_auto_20181004_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='meme',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
