# Generated by Django 2.0.7 on 2018-09-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0003_auto_20180924_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Resume',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
