# Generated by Django 2.0.6 on 2018-10-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0003_auto_20181001_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Resume',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
